name: appbdp
description: "App Mobil for BDP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  nb_utils: ^7.0.4
  flutter_localization: ^0.2.2
  url_launcher: ^6.3.0
  intl: ^0.19.0
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.0.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4
  http: ^1.2.2
  package_info_plus: ^8.0.2
  flutter_app_badge_control: ^0.0.1
  flutter_widget_from_html: ^0.15.2
  diacritic: ^0.1.6
  youtube_player_flutter: 9.0.1
  video_player: ^2.9.2
  chewie: ^1.8.5
  flutter_cached_pdfview: ^0.4.2
  flutter_downloader: ^1.11.8
  flutter_svg: ^2.0.10+1
  share_plus: ^7.2.2
  screenshot: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  pdf: ^3.11.1
  printing: ^5.13.3
  syncfusion_flutter_charts: ^27.1.57
  syncfusion_flutter_gauges: ^27.1.57
  dropdown_search: ^6.0.1
  file_picker: ^8.1.4
  flick_video_player: ^0.9.0

dependency_overrides:
  webview_flutter_android: 3.16.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - fonts/
  fonts:
    - family: exo2
      fonts:
        - asset: fonts/exo2/Exo2-Bold.ttf
        - asset: fonts/exo2/Exo2-Regular.ttf
        - asset: fonts/exo2/Exo2-Light.ttf
    - family: helvetica
      fonts:
        - asset: fonts/helvetica/Helvetica-Bold.ttf
        - asset: fonts/helvetica/Helvetica.ttf
        - asset: fonts/helvetica/Helvetica-Light.ttf